apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-injector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.27.0  # adjust as needed
    helm:
      values: |
        injector:
          enabled: true
        server:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
