apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: postgresql
  name: argocd-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-binding
  namespace: postgresql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-role
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd
