apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.4.4  # Or latest supported version
    chart: mongodb
    helm:
      values: |
        auth:
          enabled: true
          rootUser: root
          rootPassword: rootpassword
        architecture: standalone
        replicaSet:
          enabled: false
        service:
          type: ClusterIP
        persistence:
          enabled: true
          size: 5Gi
        metrics:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
