apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: 13.20.1  # or "latest"
    helm:
      values: |
        architecture: standalone
        auth:
          enabled: false  # For dev only
        persistence:
          enabled: true
          size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: mongo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
