apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-express
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/heal23/k3s-apps
    targetRevision: HEAD
    path: mongo-express
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
