apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.17.0
    helm:
      values: |
        externalURL: https://harbor.heal23.ch
        harborAdminPassword: "16032022"
        expose:
          ingress:
            enabled: true
            hosts:
              core: harbor.heal23.ch
              notary: notary.harbor.heal23.ch
            annotations:
              kubernetes.io/ingress.class: traefik
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
            tls:
              - secretName: harbor-tls
                hosts:
                  - harbor.heal23.ch
        persistence:
          enabled: true
          storageClass: "your-storage-class"
          persistentVolumeClaim:
            registry:
              size: 20Gi
            chartmuseum:
              size: 10Gi
            jobservice:
              size: 5Gi
            database:
              size: 10Gi
            redis:
              size: 5Gi
            trivy:
              size: 10Gi
        notary:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
