apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: vault
spec:
  selector:
    matchLabels:
      app: vault
  serviceName: vault
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.15.2
          command: ["vault", "server"]
          ports:
            - containerPort: 8200
              name: vault
          env:
            - name: VAULT_LOCAL_CONFIG
              value: |
                ui = true
                listener "tcp" {
                  address = "0.0.0.0:8200"
                  tls_disable = 1
                }
                storage "file" {
                  path = "/vault/data"
                }
                disable_mlock = true
          volumeMounts:
            - name: vault-storage
              mountPath: /vault/data
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
      volumes:
        - name: vault-storage
          persistentVolumeClaim:
            claimName: vault-pvc