apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tailscale
  name: tailscale
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
