apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: tailscale
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "tailscale-role"
    vault.hashicorp.com/agent-inject-secret-TS_AUTHKEY: "tailscale/ts-auth"
    vault.hashicorp.com/agent-inject-template-TS_AUTHKEY: |
      {{- with secret "tailscale/ts-auth" -}}
      {{ .Data.data.TS_AUTHKEY }}
      {{- end }}
type: Opaque
stringData:
  TS_AUTHKEY: "placeholder"  # This will be overwritten by Vault
