image:
  repository: tailscale/tailscale
  tag: latest

authKey: "VAULT_INJECTED" # Placeholder to be injected from Vault
statefulset:
  enabled: false
daemonset:
  enabled: true

env:
  TS_AUTHKEY:
    valueFrom:
      secretKeyRef:
        name: tailscale-auth
        key: TS_AUTHKEY
